#!/bin/zsh
# Mechanical part of Weekly Maintenance. Run by hand, or via /weekly-maintenance in Claude Code.
# Full agent version: Skills/Workflows/Weekly Maintenance.md (/weekly-maintenance).
set -u
cd "$(dirname "$0")/.." || exit 1
WEEK=$(date +%Y-W%V)
NOTE="Ideaverse/Calendar/${WEEK} - Weekly Review.md"
LOG="scripts/logs/weekly-${WEEK}.log"
{
  echo "=== Weekly maintenance ${WEEK} ($(date)) ==="
  python3 scripts/build_views.py
  python3 scripts/vault_lint.py
  LINT_STATUS=$?
  if [ ! -f "$NOTE" ]; then
    {
      echo "# ${WEEK} - Weekly Review (auto-stub)"
      echo ""
      echo "Generated by scripts/weekly_maintenance.sh. Run /weekly-maintenance in Claude Code to complete it."
      echo ""
      echo "## Movement this week (git)"
      git log --since="7 days ago" --oneline | sed 's/^/- /'
      echo ""
      echo "## Lint status"
      [ $LINT_STATUS -eq 0 ] && echo "Clean." || echo "ISSUES FOUND: see ${LOG}"
    } > "$NOTE"
    python3 scripts/vault_metrics.py >> "$NOTE"
    echo "created ${NOTE}"
  else
    python3 scripts/vault_metrics.py > /dev/null
  fi
  # Full agent pass (drafts the real weekly review) when the claude CLI is available
  CLAUDE_BIN="$(command -v claude 2>/dev/null || true)"
  [ -z "$CLAUDE_BIN" ] && [ -x "$HOME/.local/bin/claude" ] && CLAUDE_BIN="$HOME/.local/bin/claude"
  if [ -n "$CLAUDE_BIN" ]; then
    "$CLAUDE_BIN" -p "/weekly-maintenance" --permission-mode acceptEdits >> "scripts/logs/agent-${WEEK}.log" 2>&1 \
      || echo "agent pass failed (see agent-${WEEK}.log); mechanical results stand"
  else
    echo "claude CLI not found; mechanical pass only"
  fi
  git add "Ideaverse/Calendar" "Ideaverse/Efforts" "Maps & Manuals" "Ideaverse/Atlas" 2>/dev/null
  git commit -q -m "Weekly maintenance ${WEEK}" || echo "nothing to commit"
  git remote get-url origin >/dev/null 2>&1 && git push -q || echo "no remote configured; skipping push"
} >> "$LOG" 2>&1
